@startuml

start

:detect floor parameters;
:remove far away points;
:remove close points;
:find first plane orthogonal to floor;
:remove its points from the pointcloud;

repeat
:find second plane orthogonal to the first plane;
repeat while (second plane orthogonal to floor plane) is (no) not (yes)

stop

@enduml
